host: cloud08.core.wits.ac.za
serviceAccounts:
  monitoring:
    password: ""
deployments:
  auth:
    password: ""
  backup:
    password: ""
  fileBroker:
    password: ""
  fileStorage:
    password: ""
  jobHistory:
    password: ""
  scheduler:
    password: ""
  serviceLocator:
    password: ""
  sessionDb:
    password: ""
  sessionWorker:
    password: ""
  toolbox:
    password: ""
  typeService:
    password: ""
  webServer:
    password: ""
auth-postgresql:
  postgresqlPassword: ""
job-history-postgresql:
  postgresqlPassword: ""
session-db-postgresql:
  postgresqlPassword: ""
users:
  admin:
    password: ""
  chipster:
    password: ""
  example_session_owner:
    password: ""
  support_session_owner:
    password: ""
  regan:
    password: "myPassword"
tokens:
  auth:
    privateKey: |-
      -----BEGIN EC PRIVATE KEY-----
      MjPXs7L8wm1AT1FmS9mrqUXAiOOgqjKYKV9/cdLQQCCck2AMA3IHcAgEBBEIAAkQ
      qxo/Q30t3Oo4M4UV5+W7fZBygGOSPw+qsDFPpDeMKXFCF9vfiTJZkvowYFK4EEAC
      kA7this/is/fake+please/do/not/copy/or/you+will+be/disappointedPf
      680mKMVwGhh/nWyBcwAl+NLEHvfcpK4keNQjDRrburGp8NPF+5LzKameDgqxZQpj
      MNv9F9zXHJYABABjRJ2DAMw==
      -----END EC PRIVATE KEY-----
