host: 146.141.240.75
deployments:
  auth:
    password: XXXXXX
  backup:
    password: XXXXXX
  fileBroker:
    password: XXXXXX
  fileStorage:
    password: XXXXXX
  jobHistory:
    password: XXXXXX
  s3Storage:
    password: XXXXXX
  scheduler:
    password: XXXXXX
  serviceLocator:
    password: XXXXXX
  sessionDb:
    password: XXXXXX
  sessionWorker:
    password: XXXXXX
  toolbox:
    password: XXXXXX
    configs:
      toolbox-runtime-command-R-4.2.3-cellbender: /opt/chipster/tools/R-4.2.3/bin/R
      toolbox-runtime-image-R-4.2.3-cellbender: comp-r-4-2-3-cellbender
      toolbox-runtime-tools-bin-path-R-4.2.3-cellbender: tools-bin
  typeService:
    password: XXXXXX
  webServer:
    password: XXXXXX
serviceAccounts:
  monitoring:
    password: XXXXXX
auth-postgresql:
  postgresqlPassword: XXXXXX
  auth:
    postgresPassword: XXXXXX
job-history-postgresql:
  postgresqlPassword: XXXXXX
  auth:
    postgresPassword: XXXXXX
session-db-postgresql:
  postgresqlPassword: XXXXXX
  auth:
    postgresPassword: XXXXXX
users:
  admin:
    password: XXXXXX
  chipster:
    password: XXXXXX
  example_session_owner:
    password: XXXXXX
  support_session_owner:
    password: XXXXXX
  regan:
    password: XXXXXX
  phele:
    password: XXXXXX
  emma:
    password: XXXXXX
  maria:
    password: XXXXXX
toolsBin:
  version: chipster-4.9.0
  volumeSize: 500Gi
  hostPath: /mnt/data/chipster/tools-bin

tools:
  hostPath: /opt/chipster/toolbox/tools
databases:
  auth:
    hostPath: "/mnt/data/auth-postgresql"
  sessionDb:
    hostPath: "/mnt/data/session-db-postgresql"
  jobHistory:
    hostPath: "/mnt/data/job-history-postgresql"
tokens:
  auth:
    privateKey: |-
      -----BEGIN EC PRIVATE KEY-----
      XXXXXX
      -----END EC PRIVATE KEY-----
